### ISSUE TITLE
Personnes intéressées : impossible de changer ou supprimer la date

### ISSUE THREAD

**Issue by real34** [lachouettecoop/chouette-admin-chouettos#35]
dans la liste des personnes intéressées

**Comment by glukose** [comment]
Je n'ai pas pu reproduire et la modification fonctionne.

**Comment by real34** [comment]
Oui, en effet. J'avais demandé confirmation également car je n'y étais pas parvenu et finalement la personne l'ayant remonté n'y été plus arrivée non plus et devait réessayer de voir.

Merci.
