### ISSUE TITLE
Encart « Personne rattachée »

### ISSUE THREAD

**Issue by real34** [lachouettecoop/chouette-admin-chouettos#4]
Afin de pouvoir faire un suivi des personnes rattachées, il faudrait pouvoir saisir des informations sur la personne rattachée à un·e Chouettos.

* dans la fiche d'une personne
* ajouter les informations dans les exports
* idéalement pouvoir chercher sur le nom / prénom de la personne rattachée (soit à inclure dans la [recherche rapide](https://github.com/lachouettecoop/chouette-admin-chouettos/blob/master/symfony/src/Glukose/UserBundle/Admin/UserAdmin.php#L293) actuelle, soit en faire une similaire dédiée aux personnes rattachées)

## Champs nécessaires

* Nom
* Prénom
* Téléphone
* Email
* Date de naissance
* Photo (cf #7)

**Comment by real34** [comment]
## Notes techniques : 

Il faudrait garder en tête le fait que potentiellement il puisse y avoir plusieurs personnes rattachées à terme (par exemple plusieurs enfants).

Aussi il me semble pertinent d'implémenter cela avec une entité séparée, même si la relation est de type `hasOne` plutôt que `hasMany` pour l'instant.

**Comment by real34** [comment]
Pour info
> 10 - Ajout d'une ou plusieurs Personne(s) Rattachée(s) sur la fiche d'un Chouettos avec les champs suivants :
> 
>    - photo
> 
>    - Nom
> 
>    - Prénom
> 
>    - Date de naissance
> 
>    - potentiellement E-mail, celà reste à déterminer par BdM / COM
> 
> => Action pour Pierre : ajouter les Personne(s) Rattachée(s) et leurs champs

**Comment by real34** [comment]
Redevient important. Il faudra également voir comment cela doit se gérer pour les impressions de badge.

**Comment by owl40** [comment]
> 
> 
> Pour info
> 
> > 10 - Ajout d'une ou plusieurs Personne(s) Rattachée(s) sur la fiche d'un Chouettos avec les champs suivants :
> > 
> > * photo
> > * Nom
> > * Prénom
> > * Date de naissance
> > * potentiellement E-mail, celà reste à déterminer par BdM / COM
> > 
> > => Action pour Pierre : ajouter les Personne(s) Rattachée(s) et leurs champs

A ce jour, Photo, Nom et Prénom sont des données que le BdM compte recueillir obligatoirement pour le BdM. Date de naissance et E-mail sont des champs à laisser facultatifs.

**Comment by glukose** [comment]
Ready to ship dans la prochaine release !
