### ISSUE TITLE
Rattacher une photo aux membres

### ISSUE THREAD

**Issue by real34** [lachouettecoop/chouette-admin-chouettos#7]
Afin de pouvoir imprimer des badges, l'application doit permettre de conserver les photos prises durant les souscriptions en les rattachants à un·e Chouettos.

Il faut pouvoir:

* ajouter une photo à un compte
* supprimer la photo rattachée à un compte
* modifier la photo
* la consulter dans l'interface (page de détail + liste ?)
* idem pour la personne rattachée (cf #4)

**Comment by real34** [comment]
Ne maîtrisant pas trop l'upload dans Symfony, j'apprécierai bien un coup de main sur cette partie là !

**Comment by glukose** [comment]
Je pourrais m'en occuper fin aout si ce n'est pas trop urgent ;)

**Comment by real34** [comment]
Cela serait top ! Je pense avoir beaucoup d'autres choses à faire d'ici là, et m'y mettrait début Septembre si jamais tu n'as pas pu y consacrer du temps.
